name: deploy
on:
    push:
        branches:
            - master
jobs:
    build:
        name: Build and deploy gh-pages
        env:
            MY_SECRET   : ${{secrets.COMMIT_TOKEN}}
            USER_NAME   : asika32764
            USER_EMAIL  : asika32764@gmail.com
            PUBLISH_DIR : .
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v1
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: 8.0
            - name: Install Vaseman
              run: composer global require asika/vaseman ^4.0 --prefer-dist --no-suggest --no-progress
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: build
              run: |
                  npm i yarn -g
                  cd .vaseman
                  yarn install
                  PATH="$PATH:$COMPOSER_VENDOR/bin/" yarn build:prod
                  cd ..
            - name: Commit files
              run: |
                  cd .vaseman
                  yarn build:prod
                  cd ..
                  rm .gitignore
                  cp .vaseman/build/gitignore.dist .gitignore
                  git init
                  git config --local user.name $USER_NAME
                  git config --local user.email $USER_EMAIL
                  git status
                  git checkout -b gh-pages
                  git add --all
                  git commit -m "deploy to Github pages"
                  git push origin gh-pages -f
                  echo 🤘 deploy gh-pages complete.
